/**
 * Error codes returned to clients as `{ "code": "...", "params": { ... } }`.
 * The backend never returns user-facing text; the mobile app maps each code to
 * an i18n key (mobile/src/api/error-messages.ts). Keep both lists in sync.
 */
export const ErrorCode = {
  // Generic
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  RATE_LIMITED: 'RATE_LIMITED',
  SETTINGS_INVALID: 'SETTINGS_INVALID',

  // Registration, sign-in and identity (docs/01-biznes-qoidalar.md §2)
  AUTH_REFERRAL_REQUIRED: 'AUTH_REFERRAL_REQUIRED',
  AUTH_REFERRAL_INVALID: 'AUTH_REFERRAL_INVALID',
  AUTH_PHONE_TAKEN: 'AUTH_PHONE_TAKEN',
  AUTH_EMAIL_TAKEN: 'AUTH_EMAIL_TAKEN',
  AUTH_WEAK_PASSWORD: 'AUTH_WEAK_PASSWORD',
  AUTH_OTP_INVALID: 'AUTH_OTP_INVALID',
  AUTH_OTP_EXPIRED: 'AUTH_OTP_EXPIRED',
  AUTH_OTP_TOO_EARLY: 'AUTH_OTP_TOO_EARLY',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_SESSION_INVALID: 'AUTH_SESSION_INVALID',
  AUTH_IDENTITY_REQUIRED: 'AUTH_IDENTITY_REQUIRED',
  AUTH_IDENTITY_ALREADY_VERIFIED: 'AUTH_IDENTITY_ALREADY_VERIFIED',
  AUTH_IDENTITY_FAILED: 'AUTH_IDENTITY_FAILED',
  AUTH_AGE_RESTRICTED: 'AUTH_AGE_RESTRICTED',
  AUTH_DUPLICATE_PERSON: 'AUTH_DUPLICATE_PERSON',

  // Orders, wallet, tax (docs/01-biznes-qoidalar.md §3–§9)
  USER_BLOCKED: 'USER_BLOCKED',
  UPLOAD_INVALID: 'UPLOAD_INVALID',
  ORDER_ROLE_REQUIRED: 'ORDER_ROLE_REQUIRED',
  ORDER_OWN: 'ORDER_OWN',
  ORDER_NOT_AVAILABLE: 'ORDER_NOT_AVAILABLE',
  ORDER_STATUS_CONFLICT: 'ORDER_STATUS_CONFLICT',
  ORDER_TIME_INVALID: 'ORDER_TIME_INVALID',
  ORDER_CATEGORY_INVALID: 'ORDER_CATEGORY_INVALID',
  ORDER_PAYMENT_METHOD_DISABLED: 'ORDER_PAYMENT_METHOD_DISABLED',
  ORDER_CANCEL_REASON_REQUIRED: 'ORDER_CANCEL_REASON_REQUIRED',
  ORDER_PAYMENT_METHOD_MISMATCH: 'ORDER_PAYMENT_METHOD_MISMATCH',
  CHAT_NOT_AVAILABLE: 'CHAT_NOT_AVAILABLE',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_CUSTOMER_CONFIRMATION_REQUIRED: 'ORDER_CUSTOMER_CONFIRMATION_REQUIRED',
  ORDER_EXECUTOR_CONFIRMATION_REQUIRED: 'ORDER_EXECUTOR_CONFIRMATION_REQUIRED',
  WALLET_INSUFFICIENT_TO_ACCEPT: 'WALLET_INSUFFICIENT_TO_ACCEPT',
  WALLET_INSUFFICIENT_FUNDS: 'WALLET_INSUFFICIENT_FUNDS',
  WALLET_WITHDRAW_EXCEEDS_LIMIT: 'WALLET_WITHDRAW_EXCEEDS_LIMIT',
  TAX_METHOD_REQUIRED: 'TAX_METHOD_REQUIRED',
  TAX_METHOD_DISABLED: 'TAX_METHOD_DISABLED',
  TAX_CERTIFICATE_REQUIRED: 'TAX_CERTIFICATE_REQUIRED',
  TAX_VERIFICATION_PENDING: 'TAX_VERIFICATION_PENDING',
  TAX_ALREADY_DECIDED: 'TAX_ALREADY_DECIDED',
  XOLIS_NOT_AVAILABLE: 'XOLIS_NOT_AVAILABLE',

  // Payments and cards (docs/01-biznes-qoidalar.md §5, §7)
  PAYMENT_AMOUNT_INVALID: 'PAYMENT_AMOUNT_INVALID',
  PAYMENT_PROVIDER_UNAVAILABLE: 'PAYMENT_PROVIDER_UNAVAILABLE',
  PAYMENT_NOT_AVAILABLE: 'PAYMENT_NOT_AVAILABLE',
  CARD_INVALID: 'CARD_INVALID',
  CARD_NOT_SUPPORTED: 'CARD_NOT_SUPPORTED',
  CARD_CODE_INVALID: 'CARD_CODE_INVALID',
  CARD_DECLINED: 'CARD_DECLINED',
  CARD_NOT_FOUND: 'CARD_NOT_FOUND',
  WITHDRAWALS_DISABLED: 'WITHDRAWALS_DISABLED',

  // Admin / super admin (stage 7)
  DISPUTE_NOT_DISPUTED: 'DISPUTE_NOT_DISPUTED',
  DISPUTE_ALREADY_DECIDED: 'DISPUTE_ALREADY_DECIDED',
  DISPUTE_DECISION_NOT_ALLOWED: 'DISPUTE_DECISION_NOT_ALLOWED',
  DISPUTE_APPROVAL_NOT_PENDING: 'DISPUTE_APPROVAL_NOT_PENDING',
  ORDER_MODERATE_NOT_CANCELLABLE: 'ORDER_MODERATE_NOT_CANCELLABLE',
  CATEGORY_SLUG_TAKEN: 'CATEGORY_SLUG_TAKEN',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  STAFF_USER_NOT_FOUND: 'STAFF_USER_NOT_FOUND',
  STAFF_IDENTITY_REQUIRED: 'STAFF_IDENTITY_REQUIRED',
  STAFF_ALREADY_SUPER_ADMIN: 'STAFF_ALREADY_SUPER_ADMIN',
  STAFF_PERMISSION_INVALID: 'STAFF_PERMISSION_INVALID',
  PERMISSION_REQUEST_INVALID: 'PERMISSION_REQUEST_INVALID',
  PERMISSION_REQUEST_NOT_PENDING: 'PERMISSION_REQUEST_NOT_PENDING',
  USER_ALREADY_BLOCKED: 'USER_ALREADY_BLOCKED',
  USER_NOT_BLOCKED: 'USER_NOT_BLOCKED',
  BROADCAST_RATE_LIMITED: 'BROADCAST_RATE_LIMITED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

/** Error parameters. Money is passed as `bigint` tiyin and serialized as a decimal string. */
export type ErrorParams = Record<string, string | number | boolean | bigint | null>;

/** Wire format of every error response. */
export interface ErrorBody {
  code: ErrorCode;
  params: Record<string, string | number | boolean | null>;
}
