/**
 * Error codes returned to clients as `{ "code": "...", "params": { ... } }`.
 * The backend never returns user-facing text; the mobile app maps each code to
 * an i18n key (mobile/src/api/error-messages.ts). Keep both lists in sync.
 */
export const ErrorCode = {
  // Generic
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  RATE_LIMITED: 'RATE_LIMITED',
  SETTINGS_INVALID: 'SETTINGS_INVALID',

  // Registration, sign-in and identity (docs/01-biznes-qoidalar.md §2)
  AUTH_REFERRAL_REQUIRED: 'AUTH_REFERRAL_REQUIRED',
  AUTH_REFERRAL_INVALID: 'AUTH_REFERRAL_INVALID',
  AUTH_PHONE_TAKEN: 'AUTH_PHONE_TAKEN',
  AUTH_EMAIL_TAKEN: 'AUTH_EMAIL_TAKEN',
  AUTH_WEAK_PASSWORD: 'AUTH_WEAK_PASSWORD',
  AUTH_OTP_INVALID: 'AUTH_OTP_INVALID',
  AUTH_OTP_EXPIRED: 'AUTH_OTP_EXPIRED',
  AUTH_OTP_TOO_EARLY: 'AUTH_OTP_TOO_EARLY',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_SESSION_INVALID: 'AUTH_SESSION_INVALID',
  AUTH_IDENTITY_REQUIRED: 'AUTH_IDENTITY_REQUIRED',
  AUTH_IDENTITY_ALREADY_VERIFIED: 'AUTH_IDENTITY_ALREADY_VERIFIED',
  AUTH_IDENTITY_FAILED: 'AUTH_IDENTITY_FAILED',
  AUTH_AGE_RESTRICTED: 'AUTH_AGE_RESTRICTED',
  AUTH_DUPLICATE_PERSON: 'AUTH_DUPLICATE_PERSON',

  // Orders, wallet, tax (docs/01-biznes-qoidalar.md §3–§9)
  USER_BLOCKED: 'USER_BLOCKED',
  UPLOAD_INVALID: 'UPLOAD_INVALID',
  ORDER_ROLE_REQUIRED: 'ORDER_ROLE_REQUIRED',
  ORDER_OWN: 'ORDER_OWN',
  ORDER_NOT_AVAILABLE: 'ORDER_NOT_AVAILABLE',
  ORDER_STATUS_CONFLICT: 'ORDER_STATUS_CONFLICT',
  ORDER_TIME_INVALID: 'ORDER_TIME_INVALID',
  ORDER_CATEGORY_INVALID: 'ORDER_CATEGORY_INVALID',
  ORDER_PAYMENT_METHOD_DISABLED: 'ORDER_PAYMENT_METHOD_DISABLED',
  ORDER_CANCEL_REASON_REQUIRED: 'ORDER_CANCEL_REASON_REQUIRED',
  ORDER_PAYMENT_METHOD_MISMATCH: 'ORDER_PAYMENT_METHOD_MISMATCH',
  CHAT_NOT_AVAILABLE: 'CHAT_NOT_AVAILABLE',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_CUSTOMER_CONFIRMATION_REQUIRED: 'ORDER_CUSTOMER_CONFIRMATION_REQUIRED',
  ORDER_EXECUTOR_CONFIRMATION_REQUIRED: 'ORDER_EXECUTOR_CONFIRMATION_REQUIRED',
  WALLET_INSUFFICIENT_TO_ACCEPT: 'WALLET_INSUFFICIENT_TO_ACCEPT',
  WALLET_INSUFFICIENT_FUNDS: 'WALLET_INSUFFICIENT_FUNDS',
  WALLET_WITHDRAW_EXCEEDS_LIMIT: 'WALLET_WITHDRAW_EXCEEDS_LIMIT',
  TAX_METHOD_REQUIRED: 'TAX_METHOD_REQUIRED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

/** Error parameters. Money is passed as `bigint` tiyin and serialized as a decimal string. */
export type ErrorParams = Record<string, string | number | boolean | bigint | null>;

/** Wire format of every error response. */
export interface ErrorBody {
  code: ErrorCode;
  params: Record<string, string | number | boolean | null>;
}
